### ISSUE TITLE
一些有关 mkdocs 的小问题

### ISSUE THREAD

**Issue by QiuHong-1202** [TonyCrane/PracticalSkillsTutorial#1]
首先非常感谢你的 markdown & mkdocs 使用教程，在我配置自己的 mkdocs 的时候，你的教程和仓库给了我非常大的帮助，但是我在使用 mkdocs 的时候有一些烦人的小问题，所以想请教你有没有解决的办法

1. 在混排公式和文字的时候需要手动添加换行才可以保证渲染时不出错
2. 行内公式不能作为无序列表的开头（如下图所示）
![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/0f33d02c-b537-4f69-986d-6a68d39d7869)
3. 当文件数目比较多的时候，文档 bulid 的时间减慢很多（大概20几个文档，要20秒才可以 build 完成），似乎文档构建的时候只调用了单核

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/6843cb7f-4bb1-485a-95fc-7bc0c5f51d1c)

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/f8e32f20-e8c2-43a6-b0d8-36f673973afe)

**Comment by TonyCrane** [comment]
1 2 我这里没遇到过，看了你的配置，看起来同时引入了 mathJax 和 KaTeX 的 js，是不是这里乱套了之类的，可以参考我的 note 里关于公式的配置。还不行的话把你有问题的文本源码发来我看看。

3 mkdocs 是这样的，它只会用单核单线程，感觉要么忍着要么自己写多线程/多进程，反正我是觉得多线程有 GIL、多进程麻烦效果可能还不是很好，而且反正就 build 的时间长点，就忍着了（

**Comment by QiuHong-1202** [comment]
我在本地尝试使用了你的 css 和 js 配置，问题是一样的，我发现问题1是我关闭了 smart dollar 导致的，因为 smart dollar 会导致我公式的矩阵渲染有问题，我把复现的文档上传了

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/9a43e9d9-bef0-4880-b74d-417d52e563d2)

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/b031558b-ee29-4c2b-ae97-ce624622b4ce)

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/469d999f-f1f6-44e0-84cc-85170d563e58)


- 文档地址：https://qiuhong-1202.github.io/Tutorial/BugTest/
- 源码地址：https://github.com/QiuHong-1202/CS-Document/blob/main/docs/Tutorial/BugTest.md

**Comment by TonyCrane** [comment]
行间公式上下要加空行让它单独成段

第二个问题你不要给列表前面加多余的空格啊，这是不规范的写法，以及在我这里是没问题的，你那里不行是 mdx_truly_sane_lists 这个扩展导致的

**Comment by QiuHong-1202** [comment]
噢噢原来这样，非常感谢！ 我平常习惯是用 typora 做编辑器，typora 的纠错比较好，所以有的时候就没加这些换行啥的，以为 mkdocs 也有这种自动容错的功能只是我没有开启

以及想请教一下如果不用 mdx_truly_sane_lists 的话，这种多级无序列表需要怎么实现呢（mdx_truly_sane_lists 是因为之前我的配置不支持多级的无序列表所以加的，没想到导致了这个问题）

![image](https://github.com/TonyCrane/PracticalSkillsTutorial/assets/54990261/654dff65-700c-4695-91fd-f654fb446622)
文章链接： https://blog.tonycrane.cc/p/1c1e6bbc.html

**Comment by TonyCrane** [comment]
typora 那不叫纠错比较好，我觉得那是自以为是加了语法（

但 mkdocs 用的 pymarkdown 也确实没有按 CommonMark 标准（

多级无序列表不是直接写多级就可以吗：

```markdown
- a
    - b
    - c
    - d
- e
```

<img width="528" alt="image" src="https://github.com/TonyCrane/PracticalSkillsTutorial/assets/44120331/dacf718e-6523-4185-8884-296f8e9b2495">
<img width="276" alt="image" src="https://github.com/TonyCrane/PracticalSkillsTutorial/assets/44120331/82523a24-45cb-409e-af4a-7cf26305528d">

**Comment by QiuHong-1202** [comment]
破案了，typora 的 tab 缩进是两个空格，mkdocs 要是四个空格才会生效多级无序列表，原来我这么多年写的 markdown 语法都是错的。。

我之前搜到的多级无序列表的方案是加一个 mdx_truly_sane_lists 扩展，完全没提到语法规范性问题

再次感谢!
