### ISSUE TITLE
请问这个项目用的是reveak-md哪个版本?最新的版本貌似已经不能用了

### ISSUE THREAD

**Issue by squack-dlh** [TonyCrane/PracticalSkillsTutorial#3]

**Comment by TonyCrane** [comment]
不清楚，目前我本地的是 6.1.2，头一年的老 slide 肯定比这早，如果有问题的话看一下 https://github.com/TonyCrane/slide-template/commits/master/ 的 log，可能需要修一下 template，如果 template 修了还不行可以去 https://github.com/TonyCrane/slide-template/ 提 issue
